[project]
name = "my-ai-teacher"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "rrozen", email = "robirozen@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
my-ai-teacher = "my_ai_teacher:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
